main: me.dkim19375.race.RacePlugin
name: RacePlugin
version: ${pluginVersion}
description: Racing plugin
author: dkim19375
depend: [ PlaceholderAPI ]
commands:
  race:
    description: Main command
    usage: /race help|start|checkpoint (create|remove <id>|list)|tp <rank>